Added "--all" action to backup script

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -15,6 +15,12 @@ if (( $(which duplicity &> /dev/null; echo $?) > 0 )); then
 fi
 
 case $2 in
+	--all)
+		backupCron=true
+		backupDomains=true
+		backupEmails=true
+		backupMysql=true
+		;;
 	--cron)
 		backupCron=true
 		;;
@@ -30,12 +36,12 @@ case $2 in
 	-h)
 		echo "OpenZula server utilities"
 		echo "Usage:"
-		echo -e "\t$scriptName backup [--cron --domains --emails --mysql]\n"
+		echo -e "\t$scriptName backup [--all|--cron --domains --emails --mysql]\n"
 		echo "Report bugs to <alex@openzula.org>"
 		exit 0
 		;;
 	*)
-		echo "Invalid action '$2'. Use '--cron', '--domains', '--emails' or '--mysql'" >&2
+		echo "Invalid action '$2'. Use '--all', '--cron', '--domains', '--emails' or '--mysql'" >&2
 		exit 1
 		;;
 esac
