Changed odd var name to something more consistent

diff --git a/domain b/domain
--- a/domain
+++ b/domain
@@ -233,13 +233,13 @@ actionDelete() {
 		exit 1
 	fi
 
-	stateFilePath=$cfgVarStateDir/domains/$optDomain
-	if [[ ! -f $stateFilePath ]]; then
-		echo "Unable to find '$stateFilePath'" >&2
+	credentialsFile=$cfgVarStateDir/domains/$optDomain
+	if [[ ! -f $credentialsFile ]]; then
+		echo "Unable to find '$credentialsFile'" >&2
 		exit 2
 	fi
-	domainPath=$(grep "^path =" "$stateFilePath" | cut -d" " -f3)
-	user=$(grep "^user =" "$stateFilePath" | cut -d" " -f3)
+	domainPath=$(grep "^path =" "$credentialsFile" | cut -d" " -f3)
+	user=$(grep "^user =" "$credentialsFile" | cut -d" " -f3)
 
 	## Remove MySQL Database if needed (and the user)
 	if [[ $optRemoveMysql = true && -f $domainPath/.ozsrvutils-mysql ]]; then
@@ -259,7 +259,7 @@ actionDelete() {
 
 	## Remove physical files
 	rm -rf "$domainPath"
-	unlink "$cfgVarStateDir/domains/$optDomain"
+	unlink "$credentialsFile"
 
 	## Run any additional files needed
 	export OZ_USER=$user OZ_DOMAIN_NAME=$optDomain OZ_DOMAIN_PATH=$domainPath
diff --git a/email b/email
--- a/email
+++ b/email
@@ -195,9 +195,9 @@ actionDelete()
 ##
 actionChpasswd()
 {
-	stateFilePath=$cfgVarStateDir/emails/$optEmail
-	if [[ ! -f $stateFilePath ]]; then
-		echo "Unable to find '$stateFilePath'" >&2
+	credentialsFile=$cfgVarStateDir/emails/$optEmail
+	if [[ ! -f $credentialsFile ]]; then
+		echo "Unable to find '$credentialsFile'" >&2
 		exit 2
 	elif (( $(grep "^$optEmail:" /etc/dovecot/passwd > /dev/null; echo $?) == 1 )); then
 		echo "No login exists for this email address" >&2
@@ -210,7 +210,7 @@ actionChpasswd()
 	sed -i "/^$optEmail:/d" /etc/dovecot/passwd
 	echo "$optEmail":"$(dovecotpw -s SSHA -p $optPwd)" >> /etc/dovecot/passwd
 
-	sed -i "s/^password = .*/password = $optPwd/" "$stateFilePath"
+	sed -i "s/^password = .*/password = $optPwd/" "$credentialsFile"
 
 	## Run any additional files needed
 	export OZ_EMAIL=$optEmail
