Removed all email functionaility (creation & backups)
This is because we don't (and haven't for a long time) host email

diff --git a/actions/backup b/actions/backup
--- a/actions/backup
+++ b/actions/backup
@@ -2,7 +2,7 @@
 
 ###
 # OpenZula server utilities
-# --- Backups domains, emails and some system files using "duplicity"
+# --- Backups domains and other system files using "duplicity"
 #
 # Copyright (c) 2011 Alex Cartwright <alex@openzula.org>
 #
@@ -43,7 +43,6 @@ case $2 in
 		backupCron=true
 		backupDetails=true
 		backupDomains=true
-		backupEmails=true
 		backupMysql=true
 		backupPackageList=true
 		;;
@@ -56,9 +55,6 @@ case $2 in
 	--domains)
 		backupDomains=true
 		;;
-	--emails)
-		backupEmails=true
-		;;
 	--mysql)
 		backupMysql=true
 		;;
@@ -68,12 +64,12 @@ case $2 in
 	-h)
 		echo "OpenZula server utilities"
 		echo "Usage:"
-		echo -e "\t$scriptName backup [--all|--cron --details --domains --emails --mysql --package-list]\n"
+		echo -e "\t$scriptName backup [--all|--cron --details --domains --mysql --package-list]\n"
 		echo "Report bugs to <alex@openzula.org>"
 		exit 0
 		;;
 	*)
-		echo "Invalid action '$2'. Use '--all', '--cron', '--details', '--domains', '--emails', '--mysql' or '--package-list'" >&2
+		echo "Invalid action '$2'. Use '--all', '--cron', '--details', '--domains', '--mysql' or '--package-list'" >&2
 		exit 1
 		;;
 esac
@@ -111,7 +107,7 @@ duplicityArgs+=("${cfgBackupDuplicityArgs[@]}")
 
 # Function to backup a source path ($1) using the provided realm ($2). Realms
 # help separate the different things that get backed up, such as domains,
-# emails etc which suffix the "cfgBackupDest" var, e.g. $cfgBackupDest/<realm>/
+# crons etc which suffix the "cfgBackupDest" var, e.g. $cfgBackupDest/<realm>/
 #
 # An optional third argument can be passed which specifies the destination
 # subpath ($3), allowing you to organize the destination paths better. If empty
@@ -170,7 +166,7 @@ if [[ $backupCron = true ]]; then
 	duplicityBackupPath /var/spool/cron cron || exitCode=2
 fi
 
-# details of domains and emails
+# details of domains
 if [[ $backupDetails = true ]]; then
 	duplicityBackupPath "$cfgVarStateDir" details || exitCode=2
 fi
@@ -187,11 +183,6 @@ if [[ $backupDomains = true ]]; then
 			exitCode=2
 		fi
 	done
-fi
-
-# Virtual email addresses
-if [[ $backupEmails = true ]]; then
-	duplicityBackupPath /var/mail/virtual emails || exitCode=2
 fi
 
 # Domain MySQL databases and the special "mysql" database
diff --git a/actions/details b/actions/details
--- a/actions/details
+++ b/actions/details
@@ -2,7 +2,7 @@
 
 ###
 # OpenZula server utilities
-# --- Gets credentials/details of domains and email addresses
+# --- Gets credentials/details of domains
 #
 # Copyright (c) 2011 Alex Cartwright <alex@openzula.org>
 #
@@ -38,20 +38,15 @@ case $2 in
 		action=domain
 		getoptsStr=":d:h"
 		;;
-	--email)
-		action=email
-		getoptsStr=":a:h"
-		;;
 	-h)
 		echo "OpenZula server utilities"
 		echo "Usage:"
-		echo -e "\t$scriptName details --domain -d domain"
-		echo -e "\t$scriptName deatils --email -a foo@example.com\n"
+		echo -e "\t$scriptName details --domain -d domain\n"
 		echo "Report bugs to <alex@openzula.org>"
 		exit 0
 		;;
 	*)
-		echo "Invalid action '$2'. Use '--domain' or '--email'" >&2
+		echo "Invalid action '$2'. Use '--domain'" >&2
 		exit 1
 		;;
 esac
@@ -60,9 +55,6 @@ shift 2
 while getopts $getoptsStr OPTION
 do
 	case $OPTION in
-		a)
-			optEmail=$OPTARG
-			;;
 		d)
 			optDomain=${OPTARG#www.*}
 			;;
@@ -73,10 +65,6 @@ do
 				echo -e "\t$scriptName details --domain -d domain\n"
 				echo "Options:"
 				echo -e "\t-d\tDomain name of the website to get details for."
-			elif [[ $action = email ]]; then
-				echo -e "\t$scriptName details --email -a foo@example.com\n"
-				echo "Options:"
-				echo -e "\t-a\tEmail address to get details for."
 			fi
 			echo -e "\t-h\tDisplays this help text.\n"
 			echo "Report bugs to <alex@openzula.org>"
@@ -89,11 +77,9 @@ do
 	esac
 done
 
-if [[ -z $optDomain && -z $optEmail ]]; then
+if [[ -z $optDomain ]]; then
 	if [[ $action = domain ]]; then
 		echo "Invalid arguments; expecting at least '-d'. See -'h' for help text." >&2
-	else
-		echo "Invalid arguments; expecting at least '-a'. See -'h' for help text." >&2
 	fi
 	exit 1
 fi
@@ -101,8 +87,6 @@ fi
 ## Output the correct credentials file if it exists
 if [[ $action = domain ]]; then
 	credentialsFile=$cfgVarStateDir/domains/$optDomain
-else
-	credentialsFile=$cfgVarStateDir/emails/$optEmail
 fi
 
 if [[ -f $credentialsFile ]]; then
diff --git a/actions/list b/actions/list
--- a/actions/list
+++ b/actions/list
@@ -34,19 +34,18 @@
 ###
 
 case $2 in
-	--domains|--emails)
+	--domains)
 		ls -1 "$cfgVarStateDir/${2:2}/" 2> /dev/null | sort -n
 		;;
 	-h)
 		echo "OpenZula server utilities"
 		echo "Usage:"
-		echo -e "\t$scriptName list --domains"
-		echo -e "\t$scriptName list --emails\n"
+		echo -e "\t$scriptName list --domains\n"
 		echo "Report bugs to <alex@openzula.org>"
 		exit 0
 		;;
 	*)
-		echo "Invalid action '$2'. Use '--domains' or '--emails'" >&2
+		echo "Invalid action '$2'. Use '--domains'" >&2
 		exit 1
 		;;
 esac
