domain & email action now use Bash case instead of functions

diff --git a/actions/domain b/actions/domain
--- a/actions/domain
+++ b/actions/domain
@@ -104,202 +104,197 @@ if [[ ! -d $cfgVarStateDir/domains ]]; then
 	mkdir "$cfgVarStateDir/domains"
 fi
 
-##
-## Handle the 'add' action
-##
-actionAdd()
-{
-	if [[ -z $optUser || -z $optDomain ]]; then
-		echo "Invalid arguments, expects at least '-u' and '-d'. See '-h' for help text." >&2
-		exit 1
-	elif [[ -f $cfgVarStateDir/domains/$optDomain ]]; then
-		echo "Domain '$optDomain' already exists." >&2
-		exit 2
-	fi
-
-	## Get the ID of the user, create it if needed
-	optUser=${optUser:0:12}
-	userId=$(id -u "$optUser" 2> /dev/null)
-	if (( $? == 0 )); then
-		## Find another domain this user has and use the password from that
-		read -r existingStateFile < <(grep -lFx "username = $optUser" "$cfgVarStateDir"/domains/* 2> /dev/null)
-		if [[ -n $existingStateFile ]]; then
-			optPass=$(awk '/^password =/{print $3}' "$existingStateFile")
-		else
-			optPass="[no change]"
-		fi
-		usersHomeDir=$(getent passwd "$optUser" | cut -d: -f6)
-	else
-		optUser=$(echo -n "$optUser" | sed -e 's/-//g')
-		if [[ -z $optPass ]]; then
-			optPass=$(apg -d -n1 -m10 -x14 -M LCNS -E \/\'\\\")
+case $action in
+	add)
+		##
+		## Handle the 'add' action
+		##
+		if [[ -z $optUser || -z $optDomain ]]; then
+			echo "Invalid arguments, expects at least '-u' and '-d'. See '-h' for help text." >&2
+			exit 1
+		elif [[ -f $cfgVarStateDir/domains/$optDomain ]]; then
+			echo "Domain '$optDomain' already exists." >&2
+			exit 2
 		fi
 
-		## Ensure the 'www-users' group exists
-		if (( $(getent group www-users > /dev/null; echo -n $?) == 2 )); then
-			if [[ $cfgLdapEnable = true ]]; then
-				ozldap-addgroup www-users
+		## Get the ID of the user, create it if needed
+		optUser=${optUser:0:12}
+		userId=$(id -u "$optUser" 2> /dev/null)
+		if (( $? == 0 )); then
+			## Find another domain this user has and use the password from that
+			read -r existingStateFile < <(grep -lFx "username = $optUser" "$cfgVarStateDir"/domains/* 2> /dev/null)
+			if [[ -n $existingStateFile ]]; then
+				optPass=$(awk '/^password =/{print $3}' "$existingStateFile")
 			else
-				addgroup www-users
+				optPass="[no change]"
+			fi
+			usersHomeDir=$(getent passwd "$optUser" | cut -d: -f6)
+		else
+			optUser=$(echo -n "$optUser" | sed -e 's/-//g')
+			if [[ -z $optPass ]]; then
+				optPass=$(apg -d -n1 -m10 -x14 -M LCNS -E \/\'\\\")
+			fi
+
+			## Ensure the 'www-users' group exists
+			if (( $(getent group www-users > /dev/null; echo -n $?) == 2 )); then
+				if [[ $cfgLdapEnable = true ]]; then
+					ozldap-addgroup www-users
+				else
+					addgroup www-users
+				fi
+			fi
+
+			## Create the new user (gecos provided or it will be interactive)
+			usersHomeDir=$cfgUsersHomeDir/$optUser
+			if [[ $cfgLdapEnable = true ]]; then
+				ozldap-adduser "$optUser" "$optPass" "$usersHomeDir"
+			else
+				adduser \
+					--home "$usersHomeDir" \
+					--shell "$cfgUsersShell" \
+					--disabled-password \
+					--gecos "Created by ozsrvutils" \
+					"$optUser" > /dev/null
+			fi
+
+			if (( $? > 0 )); then
+				echo "Failed to add new user, exiting..." >&2
+				exit 2
+			elif [[ $cfgLdapEnable = true ]]; then
+				ozldap-addusertogroup "$optUser" www-users
+			else
+				chmod "$cfgUsersHomeDirMode" "$usersHomeDir"
+				echo -n "$optUser":"$optPass" | chpasswd
+				adduser "$optUser" www-users > /dev/null
 			fi
 		fi
 
-		## Create the new user (gecos provided or it will be interactive)
-		usersHomeDir=$cfgUsersHomeDir/$optUser
-		if [[ $cfgLdapEnable = true ]]; then
-			ozldap-adduser "$optUser" "$optPass" "$usersHomeDir"
-		else
-			adduser \
-				--home "$usersHomeDir" \
-				--shell "$cfgUsersShell" \
-				--disabled-password \
-				--gecos "Created by ozsrvutils" \
-				"$optUser" > /dev/null
+		## Setup the document root
+		domainPath=$usersHomeDir/domains/$optDomain
+		sudo -u "$optUser" mkdir -p "$domainPath/public"
+		chown :www-data "$usersHomeDir"
+
+		## Calculate the database credentials to use
+		if [[ $optCreateMysql = true ]]; then
+			sitename=$(echo -n "$optDomain" | cut -d. -f1 | sed -e 's/-//g')
+			dbPass=$(apg -d -n1 -m10 -x14 -M LCNS -E \/\'\\\")
+			if [[ -z $optDbName ]]; then
+				dbName=${optUser}_${sitename:0:51}
+			else
+				dbName=$optDbName
+			fi
+			if [[ -z $optDbUser ]]; then
+				## Work out the max length of the name part of the DB User. Use 8 chars max from the account username
+				tmpDbUser=${optUser:0:8}
+				snMaxLength=$(( 16-(${#tmpDbUser}+1) ))
+				dbUser=${sitename: 0 : $snMaxLength}-$tmpDbUser
+			else
+				dbUser=$optDbUser
+			fi
+			dbName=$(echo -n "$dbName" | sed -e 's/-//g')
+
+			# Create the actual database and user
+			mysql -u "$cfgMysqlUser" -p"$cfgMysqlPass" -h "$cfgMysqlHost" \
+				-e "CREATE DATABASE $dbName; GRANT $cfgMysqlGrantPrivs ON $dbName.* TO '$dbUser'@'$cfgMysqlGrantHost' IDENTIFIED BY '$dbPass'"
+			if (( $? == 0 )); then
+				# Store details in a file so we can get them later
+				sudo -u "$optUser" touch "$domainPath/.ozsrvutils-mysql"
+				echo -e "$dbUser\n$dbName" > "$domainPath/.ozsrvutils-mysql"
+			else
+				echo "Failed to create MySQL database '$dbName' with user '$dbUser'" >&2
+				# Empty the values since they are no longer correct and not needed
+				dbUser=
+				dbPass=
+				dbName=
+			fi
 		fi
 
-		if (( $? > 0 )); then
-			echo "Failed to add new user, exiting..." >&2
+		## Run any additional files needed
+		export OZ_USER=$optUser OZ_DOMAIN_NAME=$optDomain OZ_DOMAIN_PATH=$domainPath
+		for postFile in "$configPath"/post-domain-add.d/*; do
+			if [[ -x $postFile ]]; then
+				(cd "$configPath/post-domain-add.d" && ./$(basename "$postFile"))
+			fi
+		done
+
+		## All done!
+		sudo -u "$optUser" touch "$domainPath/.ozsrvutils"
+		credentialsFile=$cfgVarStateDir/domains/$optDomain
+
+		touch "$credentialsFile"
+		chown root:adm "$credentialsFile"
+		chmod 0640 "$credentialsFile"
+
+		echo -e "domain = $optDomain\n" \
+				"username = $optUser\n" \
+				"password = $optPass\n" \
+				"path = $domainPath" > "$credentialsFile"
+		if [[ $optCreateMysql = true ]]; then
+			echo -e "mysql_username = $dbUser\n" \
+					"mysql_password = $dbPass\n" \
+					"mysql_database = $dbName" >> "$credentialsFile"
+		fi
+
+		sed -i -e "s#^ ##g" "$credentialsFile"
+
+		## Display the newly created file to the user
+		echo -e "Created new domain for web hosting:\n"
+		cat "$credentialsFile" | sed -e "s#^#\t#g"
+		echo -e "\nPlease restart your webserver (e.g. 'apache2ctl graceful') for the website to go live."
+		;;
+
+	delete)
+		##
+		## Handle the 'delete' action
+		##
+		if [[ -z $optDomain ]]; then
+			echo "Invalid arguments, expects at least '-d'. See '-h' for help text." >&2
+			exit 1
+		fi
+
+		credentialsFile=$cfgVarStateDir/domains/$optDomain
+		if [[ ! -f $credentialsFile ]]; then
+			echo "Unable to find '$credentialsFile'" >&2
 			exit 2
-		elif [[ $cfgLdapEnable = true ]]; then
-			ozldap-addusertogroup "$optUser" www-users
-		else
-			chmod "$cfgUsersHomeDirMode" "$usersHomeDir"
-			echo -n "$optUser":"$optPass" | chpasswd
-			adduser "$optUser" www-users > /dev/null
 		fi
-	fi
+		domainPath=$(awk '/^path =/{print $3}' "$credentialsFile")
+		user=$(awk '/^user =/{print $3}' "$credentialsFile")
 
-	## Setup the document root
-	domainPath=$usersHomeDir/domains/$optDomain
-	sudo -u "$optUser" mkdir -p "$domainPath/public"
-	chown :www-data "$usersHomeDir"
-
-	## Calculate the database credentials to use
-	if [[ $optCreateMysql = true ]]; then
-		sitename=$(echo -n "$optDomain" | cut -d. -f1 | sed -e 's/-//g')
-		dbPass=$(apg -d -n1 -m10 -x14 -M LCNS -E \/\'\\\")
-		if [[ -z $optDbName ]]; then
-			dbName=${optUser}_${sitename:0:51}
-		else
-			dbName=$optDbName
-		fi
-		if [[ -z $optDbUser ]]; then
-			## Work out the max length of the name part of the DB User. Use 8 chars max from the account username
-			tmpDbUser=${optUser:0:8}
-			snMaxLength=$(( 16-(${#tmpDbUser}+1) ))
-			dbUser=${sitename: 0 : $snMaxLength}-$tmpDbUser
-		else
-			dbUser=$optDbUser
-		fi
-		dbName=$(echo -n "$dbName" | sed -e 's/-//g')
-
-		# Create the actual database and user
-		mysql -u "$cfgMysqlUser" -p"$cfgMysqlPass" -h "$cfgMysqlHost" \
-			  -e "CREATE DATABASE $dbName; GRANT $cfgMysqlGrantPrivs ON $dbName.* TO '$dbUser'@'$cfgMysqlGrantHost' IDENTIFIED BY '$dbPass'"
-		if (( $? == 0 )); then
-			# Store details in a file so we can get them later
-			sudo -u "$optUser" touch "$domainPath/.ozsrvutils-mysql"
-			echo -e "$dbUser\n$dbName" > "$domainPath/.ozsrvutils-mysql"
-		else
-			echo "Failed to create MySQL database '$dbName' with user '$dbUser'" >&2
-			# Empty the values since they are no longer correct and not needed
-			dbUser=
-			dbPass=
-			dbName=
-		fi
-	fi
-
-	## Run any additional files needed
-	export OZ_USER=$optUser OZ_DOMAIN_NAME=$optDomain OZ_DOMAIN_PATH=$domainPath
-	for postFile in "$configPath"/post-domain-add.d/*; do
-		if [[ -x $postFile ]]; then
-			(cd "$configPath/post-domain-add.d" && ./$(basename "$postFile"))
-		fi
-	done
-
-	## All done!
-	sudo -u "$optUser" touch "$domainPath/.ozsrvutils"
-	credentialsFile=$cfgVarStateDir/domains/$optDomain
-
-	touch "$credentialsFile"
-	chown root:adm "$credentialsFile"
-	chmod 0640 "$credentialsFile"
-
-	echo -e "domain = $optDomain\n" \
-			"username = $optUser\n" \
-			"password = $optPass\n" \
-			"path = $domainPath" > "$credentialsFile"
-	if [[ $optCreateMysql = true ]]; then
-		echo -e "mysql_username = $dbUser\n" \
-				"mysql_password = $dbPass\n" \
-				"mysql_database = $dbName" >> "$credentialsFile"
-	fi
-
-	sed -i -e "s#^ ##g" "$credentialsFile"
-
-	## Display the newly created file to the user
-	echo -e "Created new domain for web hosting:\n"
-	cat "$credentialsFile" | sed -e "s#^#\t#g"
-	echo -e "\nPlease restart your webserver (e.g. 'apache2ctl graceful') for the website to go live."
-}
-
-##
-## Handle the 'delete' action
-##
-actionDelete() {
-	if [[ -z $optDomain ]]; then
-		echo "Invalid arguments, expects at least '-d'. See '-h' for help text." >&2
-		exit 1
-	fi
-
-	credentialsFile=$cfgVarStateDir/domains/$optDomain
-	if [[ ! -f $credentialsFile ]]; then
-		echo "Unable to find '$credentialsFile'" >&2
-		exit 2
-	fi
-	domainPath=$(awk '/^path =/{print $3}' "$credentialsFile")
-	user=$(awk '/^user =/{print $3}' "$credentialsFile")
-
-	## Remove MySQL Database if needed (and the user)
-	if [[ $optRemoveMysql = true && -f $domainPath/.ozsrvutils-mysql ]]; then
-		dbUser=$(head -1 "$domainPath/.ozsrvutils-mysql")
-		dbName=$(tail -1 "$domainPath/.ozsrvutils-mysql")
-		mysql -u "$cfgMysqlUser" -p"$cfgMysqlPass" -h "$cfgMysqlHost" \
-			  -e "DROP DATABASE $dbName; DROP USER '$dbUser'@'$cfgMysqlGrantHost';"
-		if (( $? == 0 )); then
-			dbRemoved=true
+		## Remove MySQL Database if needed (and the user)
+		if [[ $optRemoveMysql = true && -f $domainPath/.ozsrvutils-mysql ]]; then
+			dbUser=$(head -1 "$domainPath/.ozsrvutils-mysql")
+			dbName=$(tail -1 "$domainPath/.ozsrvutils-mysql")
+			mysql -u "$cfgMysqlUser" -p"$cfgMysqlPass" -h "$cfgMysqlHost" \
+				-e "DROP DATABASE $dbName; DROP USER '$dbUser'@'$cfgMysqlGrantHost';"
+			if (( $? == 0 )); then
+				dbRemoved=true
+			else
+				dbRemoved=false
+				echo "Failed to remove MySQL database '$dbName' and/or user '$dbUser'@'$cfgMysqlGrantHost'" >&2
+			fi
 		else
 			dbRemoved=false
-			echo "Failed to remove MySQL database '$dbName' and/or user '$dbUser'@'$cfgMysqlGrantHost'" >&2
 		fi
-	else
-		dbRemoved=false
-	fi
 
-	## Remove physical files
-	rm -rf "$domainPath"
-	unlink "$credentialsFile"
+		## Remove physical files
+		rm -rf "$domainPath"
+		unlink "$credentialsFile"
 
-	## Run any additional files needed
-	export OZ_USER=$user OZ_DOMAIN_NAME=$optDomain OZ_DOMAIN_PATH=$domainPath
-	for postFile in "$configPath"/post-domain-delete.d/*; do
-		if [[ -x $postFile ]]; then
-			(cd "$configPath/post-domain-delete.d" && ./$(basename "$postFile"))
-		fi
-	done
+		## Run any additional files needed
+		export OZ_USER=$user OZ_DOMAIN_NAME=$optDomain OZ_DOMAIN_PATH=$domainPath
+		for postFile in "$configPath"/post-domain-delete.d/*; do
+			if [[ -x $postFile ]]; then
+				(cd "$configPath/post-domain-delete.d" && ./$(basename "$postFile"))
+			fi
+		done
 
-	## All done!
-	echo -e "Deleted domain for web hosting:\n"
-	echo -e "\tDomain: $optDomain"
-	echo -e "\tPath removed: $domainPath"
-	echo -e "\tRemoved MySQL database? $dbRemoved"
-	echo -e "\nPlease restart your webserver (e.g. 'apache2ctl graceful')."
-}
-
-if [[ $action = add ]]; then
-	actionAdd
-elif [[ $action = delete ]]; then
-	actionDelete
-fi
+		## All done!
+		echo -e "Deleted domain for web hosting:\n"
+		echo -e "\tDomain: $optDomain"
+		echo -e "\tPath removed: $domainPath"
+		echo -e "\tRemoved MySQL database? $dbRemoved"
+		echo -e "\nPlease restart your webserver (e.g. 'apache2ctl graceful')."
+		;;
+esac
 
 exit 0
diff --git a/actions/email b/actions/email
--- a/actions/email
+++ b/actions/email
@@ -83,145 +83,136 @@ if [[ $partUser = $partDomain || -z $partUser || -z $partDomain ]]; then
 	exit 2
 fi
 
-##
-## Handle the 'add 'action
-##
-actionAdd()
-{
-	grep -F "$optEmail" /etc/postfix/virtual/mb-maps > /dev/null
-	if (( $? == 0 )); then
-		echo "Email address already exists." >&2
-		exit 2
-	fi
-
-	## Let postfix know it's the final destination for this domain
-	grep -Fx "$partDomain" /etc/postfix/virtual/mb-domains > /dev/null
-	if (( $? == 1 )); then
-		echo "$partDomain" >> /etc/postfix/virtual/mb-domains
-		if (( $? == 1 )); then
-			echo "Failed to add domain to /etc/postfix/virtual/mb-domains" >&2
+case $action in
+	add)
+		##
+		## Handle the 'add 'action
+		##
+		grep -F "$optEmail" /etc/postfix/virtual/mb-maps > /dev/null
+		if (( $? == 0 )); then
+			echo "Email address already exists." >&2
 			exit 2
 		fi
-	fi
 
-	## Add the map in for this email address, grouping all emails together
-	lastEntryLn=$(grep -n -m1 "@$partDomain" /etc/postfix/virtual/mb-maps | cut -d: -f1)
-	if [[ -z $lastEntryLn ]]; then
-		echo -e "\n## $partDomain\n$optEmail\t\t\t$partDomain/$partUser/" >> /etc/postfix/virtual/mb-maps
-	else
-		sed -i "${lastEntryLn}a$optEmail\t\t\t$partDomain/$partUser/" /etc/postfix/virtual/mb-maps
-	fi
-
-	## Add in the username/password entry
-	password=$(apg -d -n1 -m10 -x14 -M LCNS)
-	echo "$optEmail":"$(dovecotpw -s SSHA -p $password)" >> /etc/dovecot/passwd
-
-	maildirmake.dovecot "/var/mail/virtual/$partDomain/$partUser" vmail
-	chown -R vmail:vmail "/var/mail/virtual/$partDomain"
-
-	postmap /etc/postfix/virtual/mb-maps
-	postfix reload 2> /dev/null
-
-	## Run any additional files needed
-	export OZ_EMAIL=$optEmail
-	for postFile in "$configPath"/post-email-add.d/*; do
-		if [[ -x $postFile ]]; then
-			(cd "$configPath/post-email-add.d" && ./$(basename "$postFile"))
+		## Let postfix know it's the final destination for this domain
+		grep -Fx "$partDomain" /etc/postfix/virtual/mb-domains > /dev/null
+		if (( $? == 1 )); then
+			echo "$partDomain" >> /etc/postfix/virtual/mb-domains
+			if (( $? == 1 )); then
+				echo "Failed to add domain to /etc/postfix/virtual/mb-domains" >&2
+				exit 2
+			fi
 		fi
-	done
 
-	## All done!
-	credentialsFile=$cfgVarStateDir/emails/$optEmail
-	touch "$credentialsFile"
-	chown root:adm "$credentialsFile"
-	chmod 0640 "$credentialsFile"
-
-	echo -e "address = $optEmail\n" \
-			"username = $optEmail\n" \
-			"password = $password\n" \
-			"server = $(cat /etc/mailname)" > "$credentialsFile"
-	sed -i -e "s#^ ##g" "$credentialsFile"
-
-	## Display the newly created file to the user
-	echo -e "New email address created:\n"
-	cat "$credentialsFile" | sed -e "s#^#\t#g"
-}
-
-##
-## Handle the 'delete' action
-##
-actionDelete()
-{
-	grep -F "$optEmail" /etc/postfix/virtual/mb-maps > /dev/null
-	if (( $? == 1 )); then
-		echo "Email address does not exist" >&2
-		exit 2
-	fi
-
-	sed -i "/^$optEmail/d" /etc/postfix/virtual/mb-maps /etc/dovecot/passwd
-	rm -rf "/var/mail/virtual/$partDomain/$partUser"
-
-	## See if there are any more emails addresses for this domain
-	if (( $(grep -Fc "@$partDomain" /etc/postfix/virtual/mb-maps) == 0 )); then
-		sed -i "/^## $partDomain/d" /etc/postfix/virtual/mb-maps
-		sed -i "/^$partDomain/d" /etc/postfix/virtual/mb-domains
-		rm -rf "/var/mail/virtual/$partDomain"
-	fi
-
-	## Run any additional files needed
-	export OZ_EMAIL=$optEmail
-	for postFile in "$configPath"/post-email-delete.d/*; do
-		if [[ -x $postFile ]]; then
-			(cd "$configPath/post-email-delete.d" && ./$(basename "$postFile"))
+		## Add the map in for this email address, grouping all emails together
+		lastEntryLn=$(grep -n -m1 "@$partDomain" /etc/postfix/virtual/mb-maps | cut -d: -f1)
+		if [[ -z $lastEntryLn ]]; then
+			echo -e "\n## $partDomain\n$optEmail\t\t\t$partDomain/$partUser/" >> /etc/postfix/virtual/mb-maps
+		else
+			sed -i "${lastEntryLn}a$optEmail\t\t\t$partDomain/$partUser/" /etc/postfix/virtual/mb-maps
 		fi
-	done
 
-	unlink "$cfgVarStateDir/emails/$optEmail" 2> /dev/null
-	postmap /etc/postfix/virtual/mb-maps
-	postfix reload 2> /dev/null
+		## Add in the username/password entry
+		password=$(apg -d -n1 -m10 -x14 -M LCNS)
+		echo "$optEmail":"$(dovecotpw -s SSHA -p $password)" >> /etc/dovecot/passwd
 
-	echo "Deleted email address '$optEmail'"
-}
+		maildirmake.dovecot "/var/mail/virtual/$partDomain/$partUser" vmail
+		chown -R vmail:vmail "/var/mail/virtual/$partDomain"
 
-##
-## Handle the 'chpasswd' action
-##
-actionChpasswd()
-{
-	credentialsFile=$cfgVarStateDir/emails/$optEmail
-	if [[ ! -f $credentialsFile ]]; then
-		echo "Unable to find '$credentialsFile'" >&2
-		exit 2
-	elif (( $(grep "^$optEmail:" /etc/dovecot/passwd > /dev/null; echo -n $?) == 1 )); then
-		echo "No login exists for this email address" >&2
-		exit 2
-	elif (( ${#optPwd} < 6 )); then
-		echo "Password must be >= 6 characters long" >&2
-		exit 2
-	fi
+		postmap /etc/postfix/virtual/mb-maps
+		postfix reload 2> /dev/null
 
-	sed -i "/^$optEmail:/d" /etc/dovecot/passwd
-	echo "$optEmail":"$(dovecotpw -s SSHA -p $optPwd)" >> /etc/dovecot/passwd
+		## Run any additional files needed
+		export OZ_EMAIL=$optEmail
+		for postFile in "$configPath"/post-email-add.d/*; do
+			if [[ -x $postFile ]]; then
+				(cd "$configPath/post-email-add.d" && ./$(basename "$postFile"))
+			fi
+		done
 
-	sed -i "s/^password = .*/password = $optPwd/" "$credentialsFile"
+		## All done!
+		credentialsFile=$cfgVarStateDir/emails/$optEmail
+		touch "$credentialsFile"
+		chown root:adm "$credentialsFile"
+		chmod 0640 "$credentialsFile"
 
-	## Run any additional files needed
-	export OZ_EMAIL=$optEmail
-	for postFile in "$configPath"/post-email-chpasswd.d/*; do
-		if [[ -x $postFile ]]; then
-			(cd "$configPath/post-email-chpasswd.d" && ./$(basename "$postFile"))
+		echo -e "address = $optEmail\n" \
+				"username = $optEmail\n" \
+				"password = $password\n" \
+				"server = $(cat /etc/mailname)" > "$credentialsFile"
+		sed -i -e "s#^ ##g" "$credentialsFile"
+
+		## Display the newly created file to the user
+		echo -e "New email address created:\n"
+		cat "$credentialsFile" | sed -e "s#^#\t#g"
+		;;
+
+	delete)
+		##
+		## Handle the 'delete' action
+		##
+		grep -F "$optEmail" /etc/postfix/virtual/mb-maps > /dev/null
+		if (( $? == 1 )); then
+			echo "Email address does not exist" >&2
+			exit 2
 		fi
-	done
 
-	echo "Updated email password"
-}
+		sed -i "/^$optEmail/d" /etc/postfix/virtual/mb-maps /etc/dovecot/passwd
+		rm -rf "/var/mail/virtual/$partDomain/$partUser"
 
-if [[ $action = add ]]; then
-	actionAdd
-elif [[ $action = delete ]]; then
-	actionDelete
-elif [[ $action = chpasswd ]]; then
-	actionChpasswd
-fi
+		## See if there are any more emails addresses for this domain
+		if (( $(grep -Fc "@$partDomain" /etc/postfix/virtual/mb-maps) == 0 )); then
+			sed -i "/^## $partDomain/d" /etc/postfix/virtual/mb-maps
+			sed -i "/^$partDomain/d" /etc/postfix/virtual/mb-domains
+			rm -rf "/var/mail/virtual/$partDomain"
+		fi
+
+		## Run any additional files needed
+		export OZ_EMAIL=$optEmail
+		for postFile in "$configPath"/post-email-delete.d/*; do
+			if [[ -x $postFile ]]; then
+				(cd "$configPath/post-email-delete.d" && ./$(basename "$postFile"))
+			fi
+		done
+
+		unlink "$cfgVarStateDir/emails/$optEmail" 2> /dev/null
+		postmap /etc/postfix/virtual/mb-maps
+		postfix reload 2> /dev/null
+
+		echo "Deleted email address '$optEmail'"
+		;;
+
+	chpasswd)
+		##
+		## Handle the 'chpasswd' action
+		##
+		credentialsFile=$cfgVarStateDir/emails/$optEmail
+		if [[ ! -f $credentialsFile ]]; then
+			echo "Unable to find '$credentialsFile'" >&2
+			exit 2
+		elif (( $(grep "^$optEmail:" /etc/dovecot/passwd > /dev/null; echo -n $?) == 1 )); then
+			echo "No login exists for this email address" >&2
+			exit 2
+		elif (( ${#optPwd} < 6 )); then
+			echo "Password must be >= 6 characters long" >&2
+			exit 2
+		fi
+
+		sed -i "/^$optEmail:/d" /etc/dovecot/passwd
+		echo "$optEmail":"$(dovecotpw -s SSHA -p $optPwd)" >> /etc/dovecot/passwd
+
+		sed -i "s/^password = .*/password = $optPwd/" "$credentialsFile"
+
+		## Run any additional files needed
+		export OZ_EMAIL=$optEmail
+		for postFile in "$configPath"/post-email-chpasswd.d/*; do
+			if [[ -x $postFile ]]; then
+				(cd "$configPath/post-email-chpasswd.d" && ./$(basename "$postFile"))
+			fi
+		done
+
+		echo "Updated email password"
+		;;
+esac
 
 exit 0
