Fixed a security issue in "domains" action when deleting domains + databases
A malicious user was able to trick the script into removing a completely
different and unrelated MySQL database (e.g. 'mysql' or another client). This
was possible because the stored ".ozsrvutils-mysql" file which contained the
username and password was editable by the user.

If this user had access to the file, e.g. FTP/SFTP/SCP then they could edit this
file and replace the database name with anything they wanted. The "domains"
action would then read this value and remove that database.

The ".ozsrvutils" and ".ozsrvutils" files are no longer generated, and the MySQL
details are now read from the credentials file only.

diff --git a/actions/domain b/actions/domain
--- a/actions/domain
+++ b/actions/domain
@@ -196,11 +196,7 @@ case $action in
 			# Create the actual database and user
 			mysql -u "$cfgMysqlUser" -p"$cfgMysqlPass" -h "$cfgMysqlHost" \
 				-e "CREATE DATABASE $dbName; GRANT $cfgMysqlGrantPrivs ON $dbName.* TO '$dbUser'@'$cfgMysqlGrantHost' IDENTIFIED BY '$dbPass'"
-			if (( $? == 0 )); then
-				# Store details in a file so we can get them later
-				sudo -u "$optUser" touch "$domainPath/.ozsrvutils-mysql"
-				echo -e "$dbUser\n$dbName" > "$domainPath/.ozsrvutils-mysql"
-			else
+			if (( $? > 0 )); then
 				echo "Failed to create MySQL database '$dbName' with user '$dbUser'" >&2
 				# Empty the values since they are no longer correct and not needed
 				dbUser=
@@ -218,9 +214,7 @@ case $action in
 		done
 
 		## All done!
-		sudo -u "$optUser" touch "$domainPath/.ozsrvutils"
 		credentialsFile=$cfgVarStateDir/domains/$optDomain
-
 		touch "$credentialsFile"
 		chown root:adm "$credentialsFile"
 		chmod 0640 "$credentialsFile"
@@ -228,14 +222,10 @@ case $action in
 		echo -e "domain = $optDomain\n" \
 				"username = $optUser\n" \
 				"password = $optPass\n" \
-				"path = $domainPath" > "$credentialsFile"
-		if [[ $optCreateMysql = true ]]; then
-			echo -e "mysql_username = $dbUser\n" \
-					"mysql_password = $dbPass\n" \
-					"mysql_database = $dbName" >> "$credentialsFile"
-		fi
-
-		sed -i -e "s#^ ##g" "$credentialsFile"
+				"path = $domainPath" \
+				"mysql_username = $dbUser\n" \
+				"mysql_password = $dbPass\n" \
+				"mysql_database = $dbName" | sed "s#^ ##g" > "$credentialsFile"
 
 		## Display the newly created file to the user
 		echo -e "Created new domain for web hosting:\n"
@@ -261,19 +251,19 @@ case $action in
 		user=$(awk '/^user =/{print $3}' "$credentialsFile")
 
 		## Remove MySQL Database if needed (and the user)
-		if [[ $optRemoveMysql = true && -f $domainPath/.ozsrvutils-mysql ]]; then
-			dbUser=$(head -1 "$domainPath/.ozsrvutils-mysql")
-			dbName=$(tail -1 "$domainPath/.ozsrvutils-mysql")
-			mysql -u "$cfgMysqlUser" -p"$cfgMysqlPass" -h "$cfgMysqlHost" \
-				-e "DROP DATABASE $dbName; DROP USER '$dbUser'@'$cfgMysqlGrantHost';"
-			if (( $? == 0 )); then
-				dbRemoved=true
-			else
-				dbRemoved=false
-				echo "Failed to remove MySQL database '$dbName' and/or user '$dbUser'@'$cfgMysqlGrantHost'" >&2
+		dhRemoved=false
+		if [[ $optRemoveMysql = true ]]; then
+			dbUser=$(awk '/^mysql_username =/{print $3}' "$credentialsFile")
+			dbName=$(awk '/^mysql_database =/{print $3}' "$credentialsFile")
+			if [[ -n $dbUser && -n $dbName ]]; then
+				mysql -u "$cfgMysqlUser" -p"$cfgMysqlPass" -h "$cfgMysqlHost" \
+					-e "DROP DATABASE $dbName; DROP USER '$dbUser'@'$cfgMysqlGrantHost';"
+				if (( $? == 0 )); then
+					dbRemoved=true
+				else
+					echo "Failed to remove MySQL database '$dbName' and/or user '$dbUser'@'$cfgMysqlGrantHost'" >&2
+				fi
 			fi
-		else
-			dbRemoved=false
 		fi
 
 		## Remove physical files
