Replaced the 'which' usage with the Bash built in 'type'

diff --git a/actions/email b/actions/email
--- a/actions/email
+++ b/actions/email
@@ -33,10 +33,12 @@
 # prior written authorization.
 ###
 
-if ! which postfix postmap dovecotpw &> /dev/null; then
-	echo "One or more of the following commands can not be found: postfix, postmap, dovecotpw" >&2
-	exit 2
-fi
+for dependency in postfix postmap dovecotpw; do
+	if ! type "$dependency" &> /dev/null; then
+		echo "'$dependency' was not found or does not exist" >&2
+		exit 2
+	fi
+done
 
 case $2 in
 	--add|--chpasswd|--delete)
diff --git a/ldapfuncs b/ldapfuncs
--- a/ldapfuncs
+++ b/ldapfuncs
@@ -33,10 +33,12 @@
 # prior written authorization.
 ###
 
-if ! which ldapsearch ldapadd ldapmodify ldapdelete &> /dev/null; then
-	echo "One or more of the following commands can not be found: ldapsearch ldapadd ldapmodify ldapdelete" >&2
-	exit 2
-fi
+for dependency in ldapsearch ldapadd ldapmodify ldapdelete; do
+	if ! type "$dependency" &> /dev/null; then
+		echo "'$dependency' was not found or does not exist" >&2
+		exit 2
+	fi
+done
 
 ## Setup the common arguments used for connecting
 ldapCommonArgs=(-H"$cfgLdapUri" -x -D"$cfgLdapBindDn" -y"$cfgLdapBindDnPwdFile")
