Major refactoring to all example-hook Bash scripts
Work includes far cleaner syntax, improved exit codes and error handling

diff --git a/example-hooks/post-domain-add.d/01-apache2 b/example-hooks/post-domain-add.d/01-apache2
--- a/example-hooks/post-domain-add.d/01-apache2
+++ b/example-hooks/post-domain-add.d/01-apache2
@@ -13,14 +13,16 @@
 ##    {DOMAIN_PATH}	Path to the domain (*not* the document root)
 ##
 
-if [[ -f apache2-vhost-template ]]; then
-	sed -e "s/{USER}/$OZ_USER/g" \
-		-e "s/{DOMAIN}/$OZ_DOMAIN_NAME/g" \
-		-e "s|{DOMAIN_PATH}|$OZ_DOMAIN_PATH|g" \
-		apache2-vhost-template > "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"
-	a2ensite "$OZ_DOMAIN_NAME" > /dev/null
-	exit 0
-else
-	echo "'apache2-vhost-template' does not exist, unable to create vhost config" >&2
+if ! type a2ensite &> /dev/null; then
+	echo "post-domain-add/apache2: 'a2ensite' was not found or does not exist" >&2
+	exit 2
+elif [[ ! -f apache2-vhost-template ]]; then
+	echo "post-domain-add/apache2: 'apache2-vhost-template' does not exist" >&2
 	exit 2
 fi
+
+sed -e "s/{USER}/$OZ_USER/g" \
+	-e "s/{DOMAIN}/$OZ_DOMAIN_NAME/g" \
+	-e "s|{DOMAIN_PATH}|$OZ_DOMAIN_PATH|g" \
+	apache2-vhost-template > "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"
+a2ensite "$OZ_DOMAIN_NAME" > /dev/null
diff --git a/example-hooks/post-domain-add.d/03-sftp b/example-hooks/post-domain-add.d/03-sftp
--- a/example-hooks/post-domain-add.d/03-sftp
+++ b/example-hooks/post-domain-add.d/03-sftp
@@ -22,18 +22,15 @@
 ##         ForceCommand internal-sftp
 ##
 
-if type setfacl &> /dev/null; then
-	usersHomeDir=$(getent passwd "$OZ_USER" | awk -F: '{print $6}')
-	if [[ -n $usersHomeDir ]]; then
-		chown root:"$OZ_USER" "$usersHomeDir"
-		if ! setfacl -m g:www-data:r-x "$usersHomeDir"; then
-			echo "failed to modify ACL rules on '$usersHomeDir'" >&2
-			exit 2
-		fi
-	else
-		echo "failed to modify ACL rules, unable to find users home directory" >&2
-		exit 2
-	fi
+if ! type setfacl &> /dev/null; then
+	echo "post-domain-add/sftp: 'setfacl' was not found or does not exist" >&2
+	exit 2
 fi
 
-exit 0
+usersHomeDir=$(getent passwd "$OZ_USER" | awk -F: '{print $6}')
+if [[ ! -n $usersHomeDir ]]; then
+	echo "post-domain-add/sftp: unable to find users home directory" >&2
+	exit 2
+fi
+
+chown root:"$OZ_USER" "$usersHomeDir" && setfacl -m g:www-data:r-x "$usersHomeDir"
diff --git a/example-hooks/post-domain-add.d/04-quota b/example-hooks/post-domain-add.d/04-quota
--- a/example-hooks/post-domain-add.d/04-quota
+++ b/example-hooks/post-domain-add.d/04-quota
@@ -5,8 +5,9 @@
 ## Configures quota limits for the user
 ##
 
-if type quotatool &> /dev/null; then
-	quotatool -u "$OZ_USER" -b -q1536MB -l2048MB /home
+if ! type quotatool &> /dev/null; then
+	echo "post-domain-add/quota: 'quotatool' was not found or does not exist" >&2
+	exit 2
 fi
 
-exit 0
+quotatool -u "$OZ_USER" -b -q1536MB -l2048MB /home
diff --git a/example-hooks/post-domain-add.d/05-git b/example-hooks/post-domain-add.d/05-git
--- a/example-hooks/post-domain-add.d/05-git
+++ b/example-hooks/post-domain-add.d/05-git
@@ -7,17 +7,22 @@
 ## new domain was added and be able to do all the lovely Git things with it.
 ##
 
-if type git &> /dev/null && [[ -d /etc/.git ]]; then
-	gitAuthorName=${SUDO_USER:-root}
-	export GIT_DIR=/etc/.git GIT_WORK_TREE=/etc/
-	git add "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"\
-			"/etc/apache2/sites-enabled/$OZ_DOMAIN_NAME"\
-			"/etc/opt/php53/fpm.d/$OZ_DOMAIN_NAME.conf"\
-			/etc/group\
-			/etc/gshadow\
-			/etc/passwd\
-			/etc/shadow > /dev/null
-	git commit --author="$gitAuthorName <$gitAuthorName@$(hostname -f)>" -m "ozsrvutils/domain/add: $OZ_DOMAIN_NAME" > /dev/null
+if ! type git &> /dev/null; then
+	echo "post-domain-add/git: 'git' was not found or does not exist" >&2
+	exit 2
+elif [[ ! -d /etc/.git ]]; then
+	echo "post-domain-add/git: /etc does not appear to be a Git repository" >&2
+	exit 2
 fi
 
-exit 0
+gitAuthorName=${SUDO_USER:-root}
+export GIT_DIR=/etc/.git GIT_WORK_TREE=/etc/
+
+git add "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"\
+		"/etc/apache2/sites-enabled/$OZ_DOMAIN_NAME"\
+		"/etc/opt/php53/fpm.d/$OZ_DOMAIN_NAME.conf"\
+		/etc/group\
+		/etc/gshadow\
+		/etc/passwd\
+		/etc/shadow > /dev/null
+git commit --author="$gitAuthorName <$gitAuthorName@$(hostname -f)>" -m "ozsrvutils/domain/add: $OZ_DOMAIN_NAME" > /dev/null
diff --git a/example-hooks/post-domain-delete.d/03-git b/example-hooks/post-domain-delete.d/03-git
--- a/example-hooks/post-domain-delete.d/03-git
+++ b/example-hooks/post-domain-delete.d/03-git
@@ -7,13 +7,18 @@
 ## domain was deleted and be able to do all the lovely Git things with it.
 ##
 
-if [[ -d /etc/.git ]]; then
-        gitAuthorName=${SUDO_USER:-root}
-        export GIT_DIR=/etc/.git GIT_WORK_TREE=/etc/
-        git rm "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"\
-                "/etc/apache2/sites-enabled/$OZ_DOMAIN_NAME"\
-                "/etc/opt/php53/fpm.d/$OZ_DOMAIN_NAME.conf" > /dev/null
-        git commit --author="$gitAuthorName <$gitAuthorName@$(hostname -f)>" -m "ozsrvutils/domain/delete: $OZ_DOMAIN_NAME" > /dev/null
+if ! type git &> /dev/null; then
+	echo "post-domain-delete/git: 'git' was not found or does not exist" >&2
+	exit 2
+elif [[ ! -d /etc/.git ]]; then
+	echo "post-domain-delete/git: /etc does not appear to be a Git repository" >&2
+	exit 2
 fi
 
-exit 0
+gitAuthorName=${SUDO_USER:-root}
+export GIT_DIR=/etc/.git GIT_WORK_TREE=/etc/
+
+git rm "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"\
+		"/etc/apache2/sites-enabled/$OZ_DOMAIN_NAME"\
+		"/etc/opt/php53/fpm.d/$OZ_DOMAIN_NAME.conf" > /dev/null
+git commit --author="$gitAuthorName <$gitAuthorName@$(hostname -f)>" -m "ozsrvutils/domain/delete: $OZ_DOMAIN_NAME" > /dev/null
